services:
#    task_blog.example:
#        class: Task\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

      admin.category:
        class: Task\BlogBundle\Admin\PostAdmin
        arguments: [~, Task\BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }